import React from "react";
import { useNavigate } from "react-router-dom";
import { Download, Activity, CheckCircle, MapPin, ScanLine } from "lucide-react";
import { generatePDF } from "../utils/PDFGenerator"; 

const ResultPanel = ({
  xrayImage,
  symptomResult, // Backend Fusion Result
  symptomData,   // Chat Data (Contains the AI Summary)
  backendUrl,
}) => {
  const navigate = useNavigate();

  if (!symptomResult) return null;

  // ------------------------------------------
  // 1. DATA EXTRACTION
  // ------------------------------------------
  const riskLevel = symptomResult.riskLevel || "Low Risk";
  const confidence = symptomResult.confidence || "0%";
  const action = symptomResult.recommendedAction || symptomResult.action || "Clinical Review";
  
  // FIX 1: Extract the specific text summary generated by the Chat AI
  // If the chat didn't run or failed, fall back to a generic message.
  const aiClinicalSummary = symptomData?.clinicalSummary || "No specific clinical red flags reported.";

  // FIX 2: Explicitly get the Disease Name (PNEUMONIA / TB / NORMAL)
  const aiDiagnosis = xrayImage?.prediction || symptomResult.prediction || "Clinical Screening";

  // Numeric score for the meter
  const riskScore = parseFloat(confidence) || 0;

  // Reasoning text for the UI
  const reasoning = symptomResult.details?.safetyOverride && symptomResult.details.safetyOverride !== "None"
    ? `Escalated Protocol: ${symptomResult.details.safetyOverride}`
    : `Assessment based on ${xrayImage ? "Multi-Modal Fusion (Symptoms + Imaging)" : "Clinical Symptom Profile"}.`;

  // ------------------------------------------
  // 2. PDF REPORT HANDLER
  // ------------------------------------------
  const handleDownloadReport = () => {
    const reportData = {
      _id: symptomResult.recordId || "PENDING",
      createdAt: new Date(),
      
      // Patient
      patientName: symptomData?.demographics?.name || "Anonymous",
      patientAge: symptomData?.demographics?.age,
      patientGender: symptomData?.demographics?.gender,

      // Stage 1: SYMPTOM DATA
      // *** CRITICAL FIX: Pass the AI Summary text to the PDF ***
      clinicalSummary: aiClinicalSummary, 
      symptomTags: symptomData?.tags || [],
      symptomScore: symptomData?.riskScore,
      chatHistory: symptomData?.historyLog,

      // Stage 2: DIAGNOSIS DATA
      riskLevel: riskLevel,
      confidence: confidence,
      prediction: aiDiagnosis, 
      
      // Images
      xrayImage: xrayImage?.preview || xrayImage?.originalBase64 || null, 
      gradcamImage: xrayImage?.gradcamBase64 || null, 
      
      // Probabilities
      probabilities: xrayImage?.probabilities || {
        TB: riskLevel.includes("High") ? 0.9 : 0.1, 
        PNEUMONIA: 0.1, 
        NORMAL: 0.1 
      }
    };

    generatePDF(reportData);
  };

  // ------------------------------------------
  // 3. UI HELPERS
  // ------------------------------------------
  const getRiskColor = () => {
    if (riskLevel.includes("High"))
      return "text-red-400 bg-red-900/40 border-red-700 shadow-[0_0_20px_rgba(239,68,68,0.3)]";
    if (riskLevel.includes("Moderate"))
      return "text-orange-300 bg-orange-900/40 border-orange-700 shadow-[0_0_20px_rgba(249,115,22,0.3)]";
    return "text-emerald-300 bg-emerald-900/40 border-emerald-700 shadow-[0_0_20px_rgba(16,185,129,0.3)]";
  };

  return (
    <div className="w-full bg-white/10 backdrop-blur-xl border border-white/10 rounded-3xl p-8 md:p-12 shadow-2xl animate-in fade-in slide-in-from-bottom-5 duration-700">

      {/* HEADER SECTION */}
      <div className="flex flex-col md:flex-row justify-between items-start mb-8 gap-6 border-b border-white/5 pb-8">
        
        {/* Left: Main Triage Result */}
        <div>
          <h2 className="text-3xl font-black text-white mb-3 flex items-center gap-3">
            <Activity className="text-blue-400" /> 
            {aiDiagnosis !== "Clinical Screening" ? aiDiagnosis : "Triage Assessment"}
          </h2>
          
          <div className="flex flex-wrap items-center gap-3">
             <div className={`px-6 py-2 rounded-full border text-lg font-bold uppercase tracking-widest transition-all ${getRiskColor()}`}>
               {riskLevel}
             </div>
             
             <div className="px-4 py-2 rounded-full border border-white/10 bg-white/5 text-white/60 text-sm font-medium flex items-center gap-2">
                <ScanLine size={16} className="text-blue-400"/>
                Confidence: {confidence}
             </div>
          </div>
        </div>
        
        {/* Right: Patient Badge */}
        {symptomData?.demographics && (
            <div className="text-right bg-white/5 p-4 rounded-2xl border border-white/10 min-w-[200px]">
                <p className="text-xs text-white/40 uppercase tracking-widest font-bold mb-1">Patient Profile</p>
                <p className="text-lg font-bold text-white">
                    {symptomData.demographics.name || "Anonymous"} 
                </p>
                <p className="text-white/50 text-sm font-normal">
                    {symptomData.demographics.age} Yrs / {symptomData.demographics.gender}
                </p>
            </div>
        )}
      </div>

      {/* MAIN CONTENT GRID */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">

        {/* LEFT COL: IMAGING VISUALS */}
        <div className="space-y-6">
          <div className="flex items-center justify-between">
             <h3 className="text-lg font-semibold flex items-center gap-2 text-white/90">
               <span className="bg-purple-500/20 p-2 rounded-lg text-purple-300"><Activity size={18} /></span>
               Analysis Data
             </h3>
             {aiDiagnosis !== "Clinical Screening" && (
                <span className="text-xs bg-blue-600/20 text-blue-300 px-2 py-1 rounded border border-blue-500/30">
                   AI Detected: {aiDiagnosis}
                </span>
             )}
          </div>
          
          {/* X-Ray Container */}
          {xrayImage?.preview ? (
              <div className="bg-black/40 border border-white/10 rounded-2xl p-4">
                <p className="text-[10px] uppercase text-white/50 mb-3 text-center tracking-widest">Input Scan & AI Heatmap</p>
                <div className="aspect-[4/3] bg-black/50 rounded-xl overflow-hidden border border-white/5 relative group">
                   {/* Main Image */}
                   <img 
                     src={xrayImage.preview} 
                     className="w-full h-full object-contain" 
                     alt="Original" 
                   />
                   
                   {/* Grad-CAM Overlay (Hover Effect) */}
                   {xrayImage.gradcamBase64 && (
                     <div className="absolute inset-0 bg-black/90 opacity-0 group-hover:opacity-100 transition-opacity duration-500 flex items-center justify-center">
                        <img src={xrayImage.gradcamBase64} className="w-full h-full object-contain opacity-100" alt="Heatmap" />
                        <span className="absolute bottom-4 bg-black/60 backdrop-blur-md px-3 py-1 rounded-full text-xs text-white border border-white/20">
                           AI Attention Map
                        </span>
                     </div>
                   )}
                </div>
                <p className="text-center text-[10px] text-white/30 mt-2">Hover to reveal AI attention heatmap</p>
              </div>
          ) : (
              <div className="bg-white/5 border border-white/10 rounded-2xl p-8 text-center flex flex-col items-center justify-center gap-4 min-h-[250px]">
                  <div className="p-4 bg-white/5 rounded-full text-white/20">
                      <Activity size={40} />
                  </div>
                  <div>
                    <p className="text-white text-md font-bold">Symptom-Based Analysis</p>
                    <p className="text-white/40 text-xs mt-1">No imaging data provided.</p>
                  </div>
              </div>
          )}
          
          {/* Risk Meter */}
          <div className="pt-4">
            <div className="flex justify-between items-end mb-2">
                <span className="text-xs font-bold uppercase tracking-widest text-white/50">Risk Index</span>
                <span className="text-xl font-bold text-white">{riskScore}%</span>
            </div>
            <div className="w-full h-3 bg-white/10 rounded-full overflow-hidden">
                <div 
                  className={`h-full rounded-full transition-all duration-1000 ease-out ${riskLevel.includes('High') ? 'bg-gradient-to-r from-orange-500 to-red-500' : 'bg-gradient-to-r from-blue-500 to-emerald-500'}`} 
                  style={{ width: `${riskScore}%` }}
                />
            </div>
          </div>
        </div>

        {/* RIGHT COL: CLINICAL DECISION */}
        <div className="bg-white/5 border border-white/10 rounded-2xl p-6 flex flex-col gap-6">
          <div>
            <h3 className="text-lg font-semibold mb-4 text-white/90">Clinical Decision Support</h3>
            
            {/* Reasoning Box */}
            <div className="bg-blue-500/10 border border-blue-500/20 rounded-xl p-5 text-sm text-blue-100 leading-relaxed shadow-inner mb-4">
              <span className="block mb-2 text-blue-300 font-bold text-xs uppercase tracking-widest">Reasoning</span>
              {reasoning}
            </div>

            {/* Recommended Protocol */}
            <div className={`p-4 rounded-xl border ${riskLevel.includes("High") ? "bg-red-500/10 border-red-500/30" : "bg-emerald-500/10 border-emerald-500/30"}`}>
                <div className="flex items-start gap-3">
                    <CheckCircle size={18} className={riskLevel.includes("High") ? "text-red-400" : "text-emerald-400"} />
                    <div>
                        <p className="text-xs font-bold uppercase tracking-widest text-white/50 mb-1">Recommended Protocol</p>
                        <p className="font-bold text-white text-lg leading-tight">{action}</p>
                    </div>
                </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="mt-auto grid gap-4 pt-4 border-t border-white/5">
              <button 
                onClick={handleDownloadReport}
                className="w-full flex items-center justify-center gap-3 px-6 py-4 bg-white/10 hover:bg-white/20 rounded-xl font-bold uppercase tracking-widest text-sm transition-all border border-white/10 shadow-lg hover:shadow-xl"
              >
                <Download size={18} />
                Download Medical Report
              </button>
              
              {riskLevel.includes("High") && (
                  <button
                    onClick={() => navigate("/hospital-finder")}
                    className="w-full flex items-center justify-center gap-3 px-6 py-4 bg-gradient-to-r from-red-600 to-orange-600 hover:scale-[1.02] rounded-xl font-bold uppercase tracking-widest text-sm transition-all shadow-lg shadow-red-900/30 text-white"
                  >
                    <MapPin size={18} />
                    Locate Emergency Center
                  </button>
              )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default ResultPanel;